[package]
name = "grace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
serde = { version = "1.0.152", features = ["derive"] }
# sarzak = { path = "../sarzak" }
sarzak = { git = "ssh://git@git.uberfoo.com:30001/sarzak/sarzak.git", branch = "develop" }
snafu = "0.7.4"
log = "0.4.17"
heck = "0.4.0"

[dev-dependencies]
pretty_env_logger = "0.4.0"

[net.ssh]
known_hosts = [
    "git.uberfoo.com]:30001 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLHKtv4ClrUNFI9YcF0dnHj1eOMH5fiud4bR9fMgzIYaG0H1GZEbKPkQLWU+y4FFYfuLaifZ9onAVDFALcFcF7U=",
]
